openapi: 3.0.1
servers:
  - url: http://localhost:3000/
    description: Development server
info:
  description: >-
    The specification for the Egyptian Sign Language website backend API.
  version: 1.0.0
  title: EgSL API
tags:
  - name: User Account and Session
    description: Sign in, sign up, sign out, delete account, update account info, view profile.
  - name: Password
    description: Request password reset email, get password reset token, reset password.
  - name: Root
    description: Get API root for testing and development.
  - name: Gestures and Reviews
    description: Index unreviewed gestures, review pending gesture, gesture creation
  - name: Words
    description: Create a word, destroy a word, show a word, index words.
  - name: Categories
    description: Create a category, destroy a category, show a category, index categories.

paths:
  /gestures/unreviewed/:
    get:
      security:
        - access-token: []
        - client: []
        - uid: []
      tags:
        - Gestures and Reviews
      operationId: index-unreviewed-gestures
      summary: index-unreviewed-gestures
      parameters:
        - in: query
          name: page
          schema:
            type: int
          required: false
          default: 1
          description: page number (defaults to 1)
        - in: query
          name: per_page
          schema:
            type: int
          required: false
          default: 5
          description: number of gestures per page (defaults to 5)
      responses:
        '200':
          description: >-
            returns at most 5 gesture records (*TODO* along with their videos)
            Also returns pagination-related metadata.
          content:
            application/json:
              example:
                {
                  "gestures": [
                    {
                      "id": 1,
                      "word_id": 5,
                      "user_id": 3,
                      "primary_dictionary_gesture": true,
                      "created_at": "2019-03-11T21:58:18.110Z",
                      "updated_at": "2019-03-11T21:58:18.176Z"
                    },
                    {
                      "id": 3,
                      "word_id": 2,
                      "user_id": 1,
                      "primary_dictionary_gesture": false,
                      "created_at": "2019-03-11T23:01:04.091Z",
                      "updated_at": "2019-03-11T23:01:04.097Z"
                    }
                  ],
                  "page_meta": {
                    "total_count": 3,
                    "total_pages": 1
                  }
                }
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                {
                  "error": "You do not have permission to access this endpoint."
                }
        '401':
          description: Unauthorized.
          content:
            application/json:
              example:
                {
                  "errors": [
                    "You need to sign in or sign up before continuing."
                  ]
                }
  /gestures/:
    post:
      security:
        - access-token: []
        - client: []
        - uid: []
      tags:
        - Gestures and Reviews
      operationId: create-gesture
      summary: create-gesture
      requestBody:
        description: >-
          Contains the string of the word to create the gesture for
          and the gesture video to be uploaded to create gesture record.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                word:
                  type: string
                video:
                  type: string
                  format: binary
              example:
                word: أحمر
                video: أحمر.mp4
      responses:
        '200':
          description: uploads video and returns gesture data.
          content:
            application/json:
              example:
                {
                  "id": 4,
                  "word_id": 2,
                  "user_id": 1,
                  "primary_dictionary_gesture": false,
                  "created_at": "2019-03-13T20:11:25.539Z",
                  "updated_at": "2019-03-13T20:11:25.542Z"
                }
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                {
                  "error": "You do not have permission to access this endpoint."
                }
        '401':
          description: Unauthorized.
          content:
            application/json:
              example:
                {
                  "errors": [
                    "You need to sign in or sign up before continuing."
                  ]
                }
        '404':
          description: Word record not found
          content:
            application/json:
              example:
                "Wordrecordnotfound"

  /gestures/{id}/review/:
    post:
      security:
        - access-token: []
        - client: []
        - uid: []
      tags:
        - Gestures and Reviews
      operationId: review-gesture
      summary: review-gesture
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
          required: true
          description: the id of the gesture to be reviewed.
      requestBody:
        description: contains review result
        content:
          application/json:
            schema:
              example:
                {
                  "accepted": "false",
                  "comment": "Bad lighting"
                }
      responses:
        '201':
          description: reviews gesture and returns review object
          content:
            application/json:
              example:
                {
                  "id": 3,
                  "gesture_id": 2,
                  "reviewer_id": 2,
                  "accepted": false,
                  "comment": "Bad lighting",
                  "created_at": "2019-03-13T23:22:12.199Z",
                  "updated_at": "2019-03-13T23:22:12.199Z"
                }
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                {
                  "error": "You do not have permission to access this endpoint."
                }
        '401':
          description: Unauthorized.
          content:
            application/json:
              example:
                {
                  "errors": [
                    "You need to sign in or sign up before continuing."
                  ]
                }
        '404':
          description: Record not found or already reviewed
          content:
            application/json:
              example:
                Recordnotfoundoralreadyreviewed

  /:
    get:
      security:
        - access-token: []
        - client: []
        - uid: []
      tags:
        - Root
      operationId: root
      summary: root
      responses:
        '200':
          description: returns "Hello"
          content:
            application/json:
              example:
                "Hello"
        '401':
          description: Unauthorized.
          content:
            application/json:
              example:
                {
                  "errors": [
                    "You need to sign in or sign up before continuing."
                  ]
                }
  /auth/:
    post:
      tags:
        - User Account and Session
      operationId: sign-up
      summary: sign-up
      requestBody:
        description: Contains the data for the user to be created.
        content:
          application/json:
            schema:
              example:
                email: youssefares@egsl.com
                password: password
                first_name: youssef
                last_name: fares
                image: someplace
                gender: male
                city: Cairo
                country: Egypt
                date_of_birth: 20/03/1996
                password_confirmation: password
                confirm_success_url: /
      responses:
        '422':
          description: Returns errors with the User data specified
          content:
            application/json:
              example:
                {
                  "status": "error",
                  "data": {
                    "id": null,
                    "provider": "email",
                    "uid": "",
                    "allow_password_change": false,
                    "first_name": "youssef",
                    "last_name": "fares",
                    "city": "Cairo",
                    "country": "Egypt",
                    "date_of_birth": "1996-03-20",
                    "email": "youssefares@egsl.com",
                    "gender": "male",
                    "image": "someplace",
                    "bio": null,
                    "is_reviewer": false,
                    "created_at": null,
                    "updated_at": null
                  },
                  "errors": {
                    "email": [
                      "has already been taken",
                      "has already been taken"
                    ],
                    "full_messages": [
                      "Email has already been taken",
                      "Email has already been taken"
                    ]
                  }
                }
        '200':
          description: Returns a user object inside "data" and sends confirmation email to email specified.
          content:
            application/json:
              example:
                {
                  "status": "success",
                  "data": {
                    "id": 5,
                    "provider": "email",
                    "uid": "youssefares@egsl.com",
                    "allow_password_change": false,
                    "first_name": "youssef",
                    "last_name": "fares",
                    "city": "Cairo",
                    "country": "Egypt",
                    "date_of_birth": "1996-03-20",
                    "email": "youssefares@egsl.com",
                    "gender": "male",
                    "image": "someplace",
                    "bio": null,
                    "is_reviewer": false,
                    "created_at": "2019-02-26T20:45:27.082Z",
                    "updated_at": "2019-02-26T20:45:27.082Z"
                  }
                }
    put:
      security:
        - access-token: []
        - client: []
        - uid: []
      tags:
        - User Account and Session
      operationId: update-account
      summary: update-account
      requestBody:
        description: >-
          Contains user fields to be updated.
          User can update password, but has to provide current_password, password and
          password_confirmation fields as inputs in request body.
          User email can also be editted. (FIXME:Is this a good idea?)
        content:
          application/json:
            schema:
              example:
                first_name: editted_youssef
                last_name: editted_fares
                image: editted_someplace
                gender: male
                city: Cairo
                bio: This is my new editted bio.
                country: Egypt
                date_of_birth: 20/03/1996
      responses:
        '404':
          description: User not found
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": [
                    "User not found."
                  ],
                  "status": "error"
                }
        '422':
          description: >-
            Returns errors with the User data specified.
          content:
            application/json:
              example:
                {
                  "status": "error",
                  "errors": {
                    "first_name": [
                      "can't be blank"
                    ],
                    "full_messages": [
                      "First name can't be blank"
                    ]
                  }
                }
        '200':
          description: Returns the updated user object inside "data"
          content:
            application/json:
              example:
                {
                  "status": "success",
                  "data": {
                    "id": 5,
                    "provider": "email",
                    "uid": "youssefares@egsl.com",
                    "allow_password_change": false,
                    "first_name": "editted_youssef",
                    "last_name": "editted_fares",
                    "city": "Cairo",
                    "country": "Egypt",
                    "date_of_birth": "1996-03-20",
                    "email": "youssefares@egsl.com",
                    "gender": "male",
                    "image": "edittedsomeplace",
                    "bio": "This is my new editted bio.",
                    "is_reviewer": false,
                    "created_at": "2019-02-26T20:45:27.082Z",
                    "updated_at": "2019-02-26T20:45:27.082Z"
                  }
                }
    delete:
      security:
        - access-token: []
        - client: []
        - uid: []
      tags:
        - User Account and Session
      operationId: delete-account
      summary: delete-account
      responses:
        '200':
          description: Successfully deleted user
          content:
            application/json:
              example:
                {
                  "status": "success",
                  "message": "Account with UID 'yousseffares@egsl.com' has been destroyed."
                }
        '404':
          description: User not found
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": [
                    "Unable to locate account for destruction."
                  ],
                  "status": "error"
                }
  /auth/sign_in/:
    post:
      tags:
        - User Account and Session
      operationId: sign-in
      summary: sign-in
      requestBody:
        description: Contains user email and password
        content:
          application/json:
            schema:
              example:
                {
                  "email": "youssefares@egsl.com",
                  "password": "password"
                }
      responses:
        '401':
          description: Unauthorized (Wrong credentials or unconfirmed email)
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": [
                    "Invalid login credentials. Please try again."
                  ]
                }
        '200':
          description: >-
            Returns a user object inside "data" and token information (to be sent in 
            the headers of further requests where authentication is required) in
            headers.
          headers:
            access-token:
              schema:
                type: string
              description: Access token string
            client:
              schema:
                type: string
              description: Info about api client
            uid:
              schema:
                type: string
              description: User identifier (email or omniauth token)
          content:
            application/json:
              example:
                {
                  "status": "success",
                  "data": {
                    "id": 5,
                    "provider": "email",
                    "uid": "youssefares@egsl.com",
                    "allow_password_change": false,
                    "first_name": "youssef",
                    "last_name": "fares",
                    "city": "Cairo",
                    "country": "Egypt",
                    "date_of_birth": "1996-03-20",
                    "email": "youssefares@egsl.com",
                    "gender": "male",
                    "image": "someplace",
                    "bio": null,
                    "is_reviewer": false,
                    "created_at": "2019-02-26T20:45:27.082Z",
                    "updated_at": "2019-02-26T20:45:27.082Z"
                  }
                }
  /auth/validate_token:
    get:
      security:
        - security:
        - access-token: []
        - client: []
        - uid: []
      tags:
        - User Account and Session
      operationId: validate-token
      summary: validate-token (can be used as to view profile)
      responses:
        '200':
          description: Valid authentication headers
          content:
            application/json:
              example:
                {
                  "success": true,
                  "data": {
                    "id": 1,
                    "provider": "email",
                    "uid": "yousseffares@egsl.com",
                    "allow_password_change": false,
                    "first_name": "joe",
                    "last_name": "fares",
                    "city": "Cairo",
                    "country": "Egypt",
                    "date_of_birth": "1996-03-20",
                    "email": "yousseffares@egsl.com",
                    "gender": "male",
                    "image": null,
                    "bio": null,
                    "is_reviewer": false
                  }
                }
        '401':
          description: Invalid authentication headers
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": [
                    "Invalid login credentials"
                  ]
                }
  /auth/sign_out:
    delete:
      security:
        - access-token: []
        - client: []
        - uid: []
      tags:
        - User Account and Session
      operationId: sign-out
      summary: sign-out
      responses:
        '200':
          description: Successfully signed out user
          content:
            application/json:
              example:
                {
                  "status": "success",
                }
        '404':
          description: User not found
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": [
                    "User was not found or was not logged in."
                  ]
                }
  /auth/password/:
    post:
      tags:
        - Password
      operationId: request-password-reset
      summary: request-password-reset
      requestBody:
        description: Contains user email and url to send the user to, to complete password reset.
        content:
          application/json:
            schema:
              example:
                {
                  "email": "youssefares@egsl.com",
                  "redirect_url": "http://localhost:3000/"
                }
      responses:
        '401':
          description: Email not provided.
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": [
                    "You must provide an email address."
                  ]
                }
        '200':
          description: Email sent
          content:
            application/json:
              example:
                {
                  "success": true,
                  "message": "An email has been sent to 'newemail@egsl.com' containing instructions for resetting your password."
                }
        '404':
          description: User not found
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": [
                    "Unable to find user with email 'newemail@egssddl.com'."
                  ]
                }
    put:
      tags:
        - Password
      operationId: password-reset
      summary: password-reset
      description: >-
        Note that this is another way to edit user password. The first was PUT /auth/ which
        requires you to know the former password. This endpoint however requires the correct
        authentication headers only, with access-token = a password reset token which is
        sent in the password reset email as part of the redirect link. 
        Optionally you can use this endpoint to reset password by knowing your 
        current_password as well.
        You may only use your password reset token once to reset your password.
      security:
        - access-token: []
        - client: []
        - uid: []
      parameters:
        - in: query
          name: password
          schema:
            type: string
          required: true
          description: new password
        - in: query
          name: password_confirmation
          schema:
            type: string
          required: true
          description: new password confirmation
        - in: query
          name: current_password
          schema:
            type: string
          description: >-
            user current password (not required when using password reset token as access token)
      responses:
        '401':
          description: Unauthorized (invalid authentication headers)
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": [
                    "Unauthorized"
                  ]
                }
        '422':
          description: Wrong current_password or invalid fields password or password_confirmation.
          content:
            application/json:
              example:
                {
                  "success": false,
                  "errors": {
                    "password_confirmation": [
                      "doesn't match Password"
                    ],
                    "current_password": [
                      "is invalid"
                    ],
                    "full_messages": [
                      "Password confirmation doesn't match Password",
                      "Current password is invalid"
                    ]
                  }
                }
        '200':
          description: Password changed
          content:
            application/json:
              example:
                {
                  "success": true,
                  "data": {
                    "id": 10,
                    "provider": "email",
                    "allow_password_change": false,
                    "email": "newemail@egsl.com",
                    "first_name": "youssef",
                    "last_name": "fares",
                    "gender": "male",
                    "city": "Cairo",
                    "country": "Egypt",
                    "date_of_birth": "1996-03-20",
                    "uid": "newemail@egsl.com",
                    "image": "someplace",
                    "bio": null,
                    "is_reviewer": false,
                    "created_at": "2019-03-01T13:59:30.243Z",
                    "updated_at": "2019-03-01T16:29:01.012Z"
                  },
                  "message": "Your password has been successfully updated."
                }
  /auth/password/edit:
    description: This endpoint is usually hit only by clicking on the link in the password reset email.
    get:
      tags:
        - Password
      operationId: get-password-reset-token
      summary: get-password-reset-token
      parameters:
        - in: query
          name: redirect_url
          schema:
            type: string
          required: true
          description: >-
            Should point to a form where the user can fill password and password_confirmation fields. 
        - in: query
          name: reset_password_token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: >-
            The user is redirected successfully to redirect_url specified when the
            password reset request was made (POST /auth/password/). The response
            will be that of the redirect_url.
            The response headers will contain the authentication headers for which
            access-token will equal the one-time password-reset token.
          headers:
            access-token:
              schema:
                type: string
              description: Access token string
            client:
              schema:
                type: string
              description: Info about api client
            uid:
              schema:
                type: string
              description: User identifier (email or omniauth token)
        '404':
          description: Invalid (or alread used once) password_reset_token
          content:
            application/json:
              example:
                {
                  "status": 404,
                  "error": "Not Found"
                }
  /categories/:
    post:
      tags:
        - Categories
      operationId: create-category
      summary: create-category
      requestBody:
        description: Contains category's name, optional parent and/or children categories
        required: true
        content:
          application/json:
            schema:
              example:
                {
                  "name": "watersports",
                  "parent": "sports"
                }
      responses:
        '200':
          description: Category created successfully. Returns the created category.
          content:
            application/json:
              example:
                {
                  "id": 5,
                  "name": "watersports",
                  "parent_id": 1,
                  "created_at": "2019-03-14T18:38:19.059Z",
                  "updated_at": "2019-03-14T18:38:19.059Z"
                }
        '422':
          description: Name is invalid (e.g. used or empty). Returns the errors.
          content:
            application/json:
              example:
                {
                  "name": [
                    "has already been taken"
                  ]
                } 

    get:
      tags:
        - Categories
      operationId: index-categories
      summary: index-categories
      responses:
        '200':
          description: Returns all available categories.
          content:
            application/json:
              example:
                [
                  {
                    "id": 1,
                    "name": "sports",
                    "parent_id": nil,
                    "created_at": "2019-03-14T18:38:19.059Z",
                    "updated_at": "2019-03-14T18:38:19.059Z"
                  },
                  {
                    "id": 5,
                    "name": "watersports",
                    "parent_id": 1,
                    "created_at": "2019-03-14T18:38:19.059Z",
                    "updated_at": "2019-03-14T18:38:19.059Z"
                  }
                ]
  /categories/{id}/:
    get:
      tags:
        - Categories
      operationId: show-category
      summary: show-category
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
          required: true
          description: the id of the category.
      responses:
        '200':
          description: Returns the category with the given id.
          content:
            application/json:
              example:
                {
                  "id": 5,
                  "name": "watersports",
                  "parent_id": 1,
                  "created_at": "2019-03-14T18:38:19.059Z",
                  "updated_at": "2019-03-14T18:38:19.059Z"
                }
        '404':
          description: Category not found.
          content:
            application/json:
              example:
                {
                  "id": "Record not found."
                }
    delete:
      tags:
        - Categories
      operationId: delete-category
      summary: delete-category
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
          required: true
          description: the id of the category to be deleted.
      responses:
        '200':
          description: Category deleted successfully.
          content:
            application/json:
              example:
                {
                  "result": "Category destroyed."
                }
        '404':
          description: Category not found.
          content:
            application/json:
              example:
                {
                  "id": "Record not found."
                }
  /words/:
    post:
      tags:
        - Words
      operationId: create-word
      summary: create-word
      requestBody:
        description: Contains word's name and array of categories
        required: true
        content:
          application/json:
            schema:
              example:
                {
                  "name": "football",
                  "categories": ["sports"]
                }
      responses:
        '200':
          description: Word created successfully.
          content:
            application/json:
              example:
                {
                  "id": 1,
                  "name": "football",
                  "categories": [
                    {
                      "name": "sport"
                    }
                  ]
                }
        '422':
          description: "Unprocessable entity: Invalid name or category."
          content:
            application/json:
              example:
                {
                  "name": [
                    "has already been taken"
                  ]
                }
    get:
      tags:
        - Words
      operationId: index-words
      summary: index-words
      requestBody:
        description: Contains optional category name and/or word substring.
        required: false
        content:
          application/json:
            schema:
              example:
                {
                  "category": ["sports"],
                  "query": "ball"
                }
      responses:
        '200':
          description: Returns the filtered words.
          content:
            application/json:
              example:
                [
                  {
                    "id": 1,
                    "name": "football",
                    "categories": [
                      {
                        "name": "sport"
                      }
                    ]
                  }
                ]
  /words/{id}/:
    get:
      tags:
        - Words
      operationId: show-word
      summary: show-word
      responses:
        '200':
          description: Returns requested word.
          content:
            application/json:
              example:
                {
                  "id": 1,
                  "name": "football",
                  "categories": [
                    {
                      "name": "sport"
                    }
                  ]
                }
        '404':
          description: Word not found.
          content:
            application/json:
              example:
                {
                  "id": "Record not found."
                }
    delete:
      tags:
        - Words
      operationId: delete-word
      summary: delete-word
      responses:
        '200':
          description: Word deleted successfully.
          content:
            application/json:
              example:
                {
                  "result": "Word destroyed."
                }
        '404':
          description: Word not found.
          content:
            application/json:
              example:
                {
                  "id": "Record not found."
                }
components:
  securitySchemes:
    access-token:
      type: apiKey
      in: header
      name: access-token
      description: Access token string
    client:
      type: apiKey
      in: header
      name: client
      description: Info about API client
    uid:
      type: apiKey
      in: header
      name: uid
      description: User identifier (email or omniauth token)
